services:
  postgres:
    image: postgres:latest
    container_name: go-scraping-db
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scraper -d scraping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
